from lib.Exceptions.CustomException import Error


class ModelTrainerInternalProcessingException(Error):
    """Raised when fail to communicate with Model Trainer"""
    pass